[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "llmask"
version = "0.1"
description = "A simple CLI tool"
dependencies = []

[project.scripts]
llmask = "llmask:cli_entrypoint"
