# Generated by Django 5.0.7 on 2024-08-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
