# Generated by Django 5.0.7 on 2024-08-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0002_llm_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llm',
            name='slug',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
    ]
