# Generated by Django 5.0.7 on 2024-08-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0003_alter_llm_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='llm',
            constraint=models.UniqueConstraint(fields=('provider_name', 'model_name_version'), name='unique_provider_model'),
        ),
        migrations.AddConstraint(
            model_name='llm',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_slug'),
        ),
    ]
