# Generated by Django 5.0.7 on 2024-08-05 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0004_llm_unique_provider_model_llm_unique_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LLM',
        ),
    ]
