# Generated by Django 5.0.7 on 2024-08-05 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('random_seed', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100)),
                ('model_name_version', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='llm',
            constraint=models.UniqueConstraint(fields=('provider_name', 'model_name_version'), name='unique_provider_model'),
        ),
        migrations.AddConstraint(
            model_name='llm',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_slug'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='llm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sohbat.llm'),
        ),
        migrations.AddConstraint(
            model_name='systemprompt',
            constraint=models.UniqueConstraint(fields=('prompt',), name='unique_system_prompt'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='system_prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sohbat.systemprompt'),
        ),
        migrations.AddConstraint(
            model_name='userprompt',
            constraint=models.UniqueConstraint(fields=('prompt',), name='unique_prompt'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='user_prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sohbat.userprompt'),
        ),
    ]
