# Generated by Django 5.0.7 on 2024-08-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sohbat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemprompt',
            name='name',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
    ]
