# Generated by Django 5.0.7 on 2024-08-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sohbat', '0002_systemprompt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='random_seed',
            field=models.IntegerField(default=42),
        ),
    ]
