# Generated by Django 5.0.7 on 2024-08-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sohbat', '0003_alter_interaction_random_seed'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.UniqueConstraint(fields=('llm', 'system_prompt', 'user_prompt', 'random_seed'), name='unique_interaction'),
        ),
    ]
