# Generated by Django 5.0.7 on 2024-08-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sohbat', '0004_interaction_unique_interaction'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='llm',
            name='unique_slug',
        ),
        migrations.RemoveConstraint(
            model_name='systemprompt',
            name='unique_system_prompt',
        ),
        migrations.RemoveConstraint(
            model_name='userprompt',
            name='unique_prompt',
        ),
        migrations.AlterField(
            model_name='llm',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='prompt',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='userprompt',
            name='prompt',
            field=models.TextField(unique=True),
        ),
    ]
