# Generated by Django 5.0.7 on 2024-08-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sohbat', '0005_remove_llm_unique_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='user_prompt',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='UserPrompt',
        ),
    ]
