# Generated by Django 5.0.7 on 2024-08-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sohbat', '0006_alter_interaction_user_prompt_delete_userprompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='random_seed',
            field=models.IntegerField(),
        ),
    ]
